add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$c\
$rust\
$cmd_duration\
$line_break\
$character"""

[username]
format = "(bold blue)[in]($style) "
style_user = "bold purple"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) [in](blue) "
style = "bold purple"
trim_at = "-"
ssh_only = true
disabled = false

# Third param
[directory]
read_only = " ğŸ”’"
read_only_style = "bold red"
style = "bold cyan"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "repo: "

[character]
success_symbol = "[=>](bold blue)"
error_symbol = "[=>](bold red)"

[fill]
symbol = " "

[cmd_duration]
style = "bold purple"

[package]
symbol = "ğŸ“¦"

[rust]
symbol = "ğŸ¦€"

[python]
disable = false

[c]
symbol = "î˜ "
format = '[$symbol ($version)]($style)'
